# netlify.toml

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/client/dist/index.html"
  status = 200

[build]
  command = "vite build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "14"
